---
title: "competition"
author: "Zhe Wang"
date: "2020/12/5"
output: word_document
---
```{r}
library(knitr)       
library(corrplot)     
library(caret)       
library(MASS)         
library(tidyverse)   
library(glmnet)       
library(tree)        
library(randomForest) 
library(gbm)         
library(e1071) 
```
```{r warning = F, message = F}
rm(list = ls())
feature <- read.csv("training_set_features.csv",stringsAsFactors=FALSE,na.strings=c("","NA")) 
labels <- read.csv("training_set_labels.csv",stringsAsFactors=FALSE)
full <- cbind(feature, labels[2:3])
set.seed(14)
theme_set(theme_bw()) # Set a better ggplot theme
options(digits=3) 
```


```{r}
full <- full %>% 
  dplyr::select(-employment_industry,-employment_occupation)
nrow(full)
```
```{r}
set.seed(100)
train_index = sort(sample(nrow(full),nrow(full)*.7))
train = full[train_index,]
test =  full[-train_index,]
train <- train %>%mutate_if(sapply(train, is.character), as.factor)
nrow(train)
test <- test %>%mutate_if(sapply(test, is.character), as.factor)
str(train)
```

```{r}
str(train)
```

```{r}
seasonaltrain <- train %>%dplyr::select(-h1n1_vaccine, -respondent_id)
seasonaltest <-test %>%dplyr::select(-h1n1_vaccine, -respondent_id)
h1n1train <-train %>%dplyr::select(-seasonal_vaccine, -respondent_id)
h1n1test <-test %>%dplyr::select(-seasonal_vaccine, -respondent_id)
```
#Sesonal flu
```{r}
library(ROCR)
library(Metrics)
glm <- glm(seasonal_vaccine~., data =seasonaltrain,family = "binomial")
log<-glm%>%predict(seasonaltest,type="response")
```


#H1N1
```{r}
library(ROCR)
library(Metrics)
glm1 <- glm(h1n1_vaccine~., data = h1n1train, family = "binomial")
logistic<-glm1%>%predict(data=h1n1test,type="response")
```

```{r}
df<-data.frame(
  sesonalflu=log,
  h1n1=logistic
)
write.csv(df,"/Users/apple/Desktop/submit.csv")
```



