---
title: "logistic"
author: "Zhe Wang"
date: "2020/12/6"
output: word_document
---



```{r message=F, warning=F}
library(tidyverse)
library(magrittr)
library(DescTools)
library(gridExtra)
library(pROC)
library(caret)
library(car)
library(ROCR)
```

# Load data
```{r}
trainfeatures = read_csv("training_set_features.csv")
trainlabels = read_csv("training_set_labels.csv")
full= merge(trainfeatures,trainlabels, by='respondent_id')

features = names(trainfeatures)[-1]
targets = names(trainlabels)[-1]
full[features] <- lapply(full[features], factor) 
```

# Train test split
```{r}
trainindex <- createDataPartition(full$seasonal_vaccine, p=0.8, list=FALSE)
train <- full[trainindex,]
test <- full[-trainindex,]
```
# Preprocessing
```{r}
train[features] <- lapply(train[features], addNA) 
test[features] <- lapply(test[features], addNA)
```

```{r}
seasonal = as.formula(paste("seasonal_vaccine", paste(features, collapse=" + "), sep=" ~ "))
logistic_seasonal <- glm(seasonal, data = train, family = "binomial")
spredict<-predict(logistic_seasonal,newdata=test,type="response")
mse=mean((test$seasonal_vaccine-spredict)^2)
mse
```
```{r}
h1n1 = as.formula(paste("h1n1_vaccine", paste(features, collapse=" + "), sep=" ~ "))
logistic_h1n1 <- glm(h1n1, data = train, family = "binomial")
hpredict<-predict(logistic_h1n1,newdata=test,type="response")
mse=mean((test$h1n1_vaccine-hpredict)^2)
mse
```

```{r}
ROCRpred<-prediction(spredict,test$seasonal_vaccine)
ROCRperf<-performance(ROCRpred,'tpr','fpr')
plot(ROCRperf, colorize = TRUE)
auc(test$seasonal_vaccine,spredict)
```

```{r}
ROCRpred1<-prediction(hpredict,test$h1n1_vaccine)
ROCRperf1<-performance(ROCRpred1,'tpr','fpr')
plot(ROCRperf1, colorize = TRUE)
auc(test$h1n1_vaccine,hpredict)
```
```{r}
Xtest = read_csv("test_set_features.csv")
Xtest[features] <- lapply(Xtest[features], addNA)
h1n1_prediction <- predict(logistic_h1n1, Xtest, type="response")
seasonal_prediction <- predict(logistic_seasonal, Xtest, type="response")
submission = data.frame(respondent_id = Xtest$respondent_id,
                           h1n1_vaccine = h1n1_prediction,
                           seasonal_vaccine = seasonal_prediction)
write.csv(submission,"logisticsubmit.csv", row.names = FALSE, quote=FALSE)
```
